// <auto-generated />
using System;
using AINews.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AINews.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322183711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AINews.Api.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AINews.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWhitelisted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AINews.Api.Models.ExtractedLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FetchStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NewsItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NewsItemId");

                    b.ToTable("ExtractedLinks");
                });

            modelBuilder.Entity("AINews.Api.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiInsights")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RawPostId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Relevance")
                        .HasColumnType("REAL");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RawPostId")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.HasIndex("TopicId");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("AINews.Api.Models.RawPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("RawPosts");
                });

            modelBuilder.Entity("AINews.Api.Models.ScanRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalNewsItemsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRawPostsFetched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSourcesScanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("AINews.Api.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("AINews.Api.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("AINews.Api.Models.ExtractedLink", b =>
                {
                    b.HasOne("AINews.Api.Models.NewsItem", "NewsItem")
                        .WithMany("ExtractedLinks")
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("AINews.Api.Models.NewsItem", b =>
                {
                    b.HasOne("AINews.Api.Models.RawPost", "RawPost")
                        .WithOne("NewsItem")
                        .HasForeignKey("AINews.Api.Models.NewsItem", "RawPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AINews.Api.Models.Source", "Source")
                        .WithMany("NewsItems")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AINews.Api.Models.Topic", "Topic")
                        .WithMany("NewsItems")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RawPost");

                    b.Navigation("Source");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AINews.Api.Models.RawPost", b =>
                {
                    b.HasOne("AINews.Api.Models.ScanRun", "ScanRun")
                        .WithMany("RawPosts")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AINews.Api.Models.Source", "Source")
                        .WithMany("RawPosts")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AINews.Api.Models.Source", b =>
                {
                    b.HasOne("AINews.Api.Models.Topic", "Topic")
                        .WithMany("Sources")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AINews.Api.Models.NewsItem", b =>
                {
                    b.Navigation("ExtractedLinks");
                });

            modelBuilder.Entity("AINews.Api.Models.RawPost", b =>
                {
                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("AINews.Api.Models.ScanRun", b =>
                {
                    b.Navigation("RawPosts");
                });

            modelBuilder.Entity("AINews.Api.Models.Source", b =>
                {
                    b.Navigation("NewsItems");

                    b.Navigation("RawPosts");
                });

            modelBuilder.Entity("AINews.Api.Models.Topic", b =>
                {
                    b.Navigation("NewsItems");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
